DROP TABLE IF EXISTS WEATHER_DATA;
CREATE TABLE WEATHER_DATA (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    date DATE NOT NULL,
    location_id BIGINT FOREIGN KEY,
);

DROP TABLE IF EXISTS LOCATION;
CREATE TABLE LOCATION (
     id BIGINT AUTO_INCREMENT PRIMARY KEY,
     lat INT NOT NULL,
     long INT NOT NULL,
     city VARCHAR(45) NOT NULL,
     state VARCHAR(45) NOT NULL
);

ALTER TABLE WEATHER_DATA
    ADD FOREIGN KEY (location_id)
        REFERENCES LOCATION(id);

DROP TABLE IF EXISTS WEATHER_DATA_TEMPERATURE;
CREATE TABLE WEATHER_DATA_TEMPERATURE (
    weather_data_id BIGINT,
    temperature DOUBLE NOT NULL,
);

ALTER TABLE WEATHER_DATA_TEMPERATURE
    ADD FOREIGN KEY (weather_data_id)
        REFERENCES WEATHER_DATA(id);
